### ISSUE TITLE
[Question] Debug help? pygatt central --> bluez peripheral

### ISSUE THREAD

**Issue by mhazley** [peplin/pygatt#153] opened 2017-10-05 17:48 UTC
Hi - I am having some strange issues using pygatt to talk to a Bluez peripheral that I have built on a Raspberry Pi in Python using their D-Bus interface - this is more of a question to ask for help in debugging what might be up.

Basically, I have a pygatt script running on a windows machine - The idea is to have it connect to the Bluez peripheral, subscribes to a characteristic, write a few "GO" bytes to that characteristic and then sit back and read notifications that are sent every 5 seconds. 

So far, it gets as far as writing the "GO" bytes (which the peripheral receives), but receives no notifications (even thought they are being sent).

Full log here: https://gist.github.com/mhazley/3ba4bb245dfab1c2312aa76177c6a593

I realise its a bit esoteric - I'm just looking any advice I can get on debugging this from the pygatt side as Bluez can be fairly impenetrable :smile_cat:

**Comment by peplin** [comment] 2019-03-30 22:59
I hope you were able to figure this out. This is out of my depth and the issue is old, so I hope you don't mind that I'm closing it.

**Closed by peplin** 2019-03-30 22:59 UTC
